Repository ScavStation/ScavStation, pull requests merged in 2020-02, with the labels that each got.

#256 Vent, scrubber construction QOL improvements.
  baystation12.dme
  code/controllers/subsystems/initialization/fabrication.dm
  code/controllers/subsystems/initialization/misc.dm
  code/datums/extensions/parts_stash.dm
  code/datums/supplypacks/engineering.dm
  code/game/machinery/_machines_base/machine_construction/item_chassis.dm
  code/game/machinery/_machines_base/machinery.dm
  code/game/machinery/_machines_base/stock_parts/building_material.dm
  code/game/machinery/pipe/construction.dm
  code/game/machinery/pipe/pipe_datums/pipe_datum_base.dm
  code/game/machinery/pipe/pipe_dispenser.dm
  code/game/objects/items/weapons/RPD.dm
  code/game/objects/items/weapons/circuitboards/machinery/engineering_circuits.dm
  code/modules/atmospherics/components/unary/vent_pump.dm
  code/modules/codex/entries/atmospherics.dm
  code/modules/fabrication/__fabricator_defines.dm
  code/modules/fabrication/_fabricator.dm
  code/modules/fabrication/designs/_design.dm
  code/modules/fabrication/designs/pipe/device_pipe_datums.dm
  code/modules/fabrication/designs/pipe/disposal_pipe_datums.dm
  code/modules/fabrication/designs/pipe/pipe_datum_base.dm
  code/modules/fabrication/designs/pipe/pipe_datums.dm
  code/modules/fabrication/fabricator_build.dm
  code/modules/fabrication/fabricator_intake.dm
  code/modules/fabrication/fabricator_pipe.dm
  code/modules/fabrication/fabricator_topic.dm
  code/modules/fabrication/fabricator_ui.dm
  code/modules/item_worth/worths_list.dm
  code/modules/recycling/disposal-construction.dm
  code/modules/recycling/disposalpipe.dm
  code/unit_tests/map_tests.dm
  maps/antag_spawn/ert/ert_base.dmm
  maps/antag_spawn/mercenary/mercenary_base.dmm
  maps/away/bearcat/bearcat-2.dmm
  maps/away/derelict/derelict-station.dmm
  maps/away/errant_pisces/errant_pisces.dmm
  maps/random_ruins/exoplanet_ruins/crashed_pod/crashed_pod.dmm
  maps/random_ruins/exoplanet_ruins/playablecolony/colony.dmm
  maps/tradeship/tradeship-2.dmm
  nano/templates/fabricator.tmpl
  test/check-paths.sh
Labels: do not merge

#282 Converting value lists to JSON.
  code/_helpers/global_lists.dm
  code/_helpers/lists.dm
  code/game/objects/buckling.dm
  code/game/objects/items/weapons/paint.dm
  code/game/objects/items/weapons/tools/crowbar.dm
  code/game/objects/items/weapons/tools/screwdriver.dm
  code/game/objects/items/weapons/tools/weldingtool.dm
  code/game/objects/items/weapons/tools/wirecutter.dm
  code/game/objects/items/weapons/tools/wrench.dm
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/modules/detectivework/tools/luminol.dm
  code/modules/detectivework/tools/rag.dm
  code/modules/games/boardgame.dm
  code/modules/reagents/dispenser/cartridge.dm
  code/modules/reagents/reagent_containers.dm
  code/modules/reagents/reagent_containers/blood_pack.dm
  code/modules/reagents/reagent_containers/borghydro.dm
  code/modules/reagents/reagent_containers/drinkingglass/drinkingglass.dm
  code/modules/reagents/reagent_containers/drinkingglass/glass_types.dm
  code/modules/reagents/reagent_containers/drinkingglass/shaker.dm
  code/modules/reagents/reagent_containers/dropper.dm
  code/modules/reagents/reagent_containers/food/cans.dm
  code/modules/reagents/reagent_containers/food/condiment.dm
  code/modules/reagents/reagent_containers/food/drinks.dm
  code/modules/reagents/reagent_containers/food/drinks/bottle.dm
  code/modules/reagents/reagent_containers/food/drinks/jar.dm
  code/modules/reagents/reagent_containers/food/fish.dm
  code/modules/reagents/reagent_containers/food/shaker.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/reagents/reagent_containers/food/snacks/meat.dm
  code/modules/reagents/reagent_containers/glass.dm
  code/modules/reagents/reagent_containers/glass/bottle.dm
  code/modules/reagents/reagent_containers/glass/bottle/robot.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  code/modules/reagents/reagent_containers/spray.dm
  code/modules/reagents/reagent_containers/syringes.dm
  code/modules/reagents/reagent_dispenser.dm
  code/modules/tables/interactions.dm
  code/modules/vehicles/bike.dm
  code/modules/vehicles/cargo_train.dm
  code/unit_tests/food_tests.dm
  maps/away/errant_pisces/errant_pisces.dm
Labels: do not merge

#285 Access changes to Jr Scientist, Solar access and EVA
  maps/tradeship/tradeship_areas.dm
  maps/tradeship/tradeship_jobs.dm
Labels: Jobs / Access

#271 Wide-scale structure rewrite and cleanup.
  code/controllers/subsystems/initialization/materials.dm
  code/game/objects/items/cryobag.dm
  code/game/objects/structures.dm
  code/game/objects/structures/barricade.dm
  code/game/objects/structures/catwalk.dm
  code/game/objects/structures/crates_lockers/closets/_closet_appearance_definitions.dm
  code/game/objects/structures/girders.dm
  code/game/objects/structures/grille.dm
  code/game/objects/structures/holosigns.dm
  code/game/objects/structures/lattice.dm
  code/game/objects/structures/railing.dm
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  code/game/objects/structures/stool_bed_chair_nest/stools.dm
  code/game/objects/structures/wall_frame.dm
  code/game/objects/structures/wallframe_spawner.dm
  code/game/objects/structures/windoor_assembly.dm
  code/game/objects/structures/window.dm
  code/game/objects/structures/window_spawner.dm
  code/game/turfs/simulated/wall_icon.dm
  code/game/turfs/simulated/walls.dm
  code/modules/codex/entries/structures.dm
  code/modules/materials/_materials.dm
  code/modules/materials/definitions/materials_glass.dm
  code/modules/materials/definitions/materials_metal.dm
  code/modules/materials/definitions/materials_organic.dm
  code/modules/materials/definitions/materials_other.dm
  code/modules/materials/definitions/materials_stone.dm
  code/modules/materials/definitions/materials_wood.dm
  code/modules/materials/material_recipes.dm
  code/modules/persistence/noticeboards.dm
  code/modules/power/cable.dm
  code/modules/tables/flipping.dm
  code/modules/tables/presets.dm
  code/modules/tables/rack.dm
  code/modules/tables/tables.dm
  icons/obj/grille.dmi
  icons/obj/items.dmi
  icons/obj/structures.dmi
  icons/obj/structures/girder.dmi
  icons/obj/structures/grille.dmi
  maps/random_ruins/exoplanet_ruins/monoliths/monoliths.dm
Labels: do not merge

#312 Generalizes some structure tool interactions.
  code/modules/crafting/_crafting_holder.dm
Labels: do not merge

#327 Edits to many snack objects
  code/datums/trading/food.dm
  code/modules/food/recipes_microwave.dm
  code/modules/mob/living/carbon/taste.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
Labels: Lore, do not merge

#376 Adminspawncookie is now adminspawnclam like god intended
  code/datums/communication/pray.dm
  code/modules/admin/topic.dm
Labels: Hot Feature

#379 Adds some simple baxxid headwear
  code/modules/client/preference_setup/loadout/lists/headwear.dm
  code/modules/valsalia/items/items_baxxid.dm
  icons/clothing/head/hood_long_baxxid.dmi
  icons/clothing/head/hood_short_baxxid.dmi
  icons/clothing/head/wig_big_blonde.dmi
  scavstation.dme
Labels: Hot Feature, content

#383 mapfixes
  maps/tradeship/tradeship-0.dmm
  maps/tradeship/tradeship-1.dmm
  maps/tradeship/tradeship-2.dmm
  maps/tradeship/tradeship-3.dmm
Labels: Tradeship, map
